# Generated by Django 4.2.11 on 2024-10-24 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_destination_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='share_publicly',
            new_name='share_pub',
        ),
    ]
